"""Add phone number col. in User Table

Revision ID: 7f8aa58d8cc7
Revises: 0b4a9ab04777
Create Date: 2026-02-22 23:19:56.427223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8aa58d8cc7'
down_revision: Union[str, Sequence[str], None] = '0b4a9ab04777'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Phone_number')
    # ### end Alembic commands ###
